<?php

declare(strict_types=1);

return [
    'platform' => [
        'name' => 'Android Digital Forensics Lab',
        'tagline' => 'Advanced casework platform for Android acquisition planning, anti-forensics evaluation, evidence integrity, and defensible reporting.',
        'version' => '1.0.0',
    ],
    'research_sources' => [
        [
            'id' => 'kumar-narayan-rasid-2026',
            'title' => 'Android Forensics: A Literature Review of Methodologies and Tool Efficacy',
            'authors' => 'Prince Kumar, Ritushree Narayan, Ekbal Rasid',
            'year' => 2026,
            'venue' => 'International Journal of Advanced Networking and Applications, 17(4), 7045-7054',
            'doi' => '10.35444/IJANA.2025.17407',
            'url' => 'https://www.ijana.in/papers/V17I4-7.pdf',
            'contribution' => 'Grounds the platform in Android acquisition categories, tool coverage limits, anti-forensics challenges, admissibility concerns, and future-facing evidence integrity patterns.',
        ],
        [
            'id' => 'sanna-2026-thesis',
            'title' => 'Artificial Intelligence for Android Stealth-Attack Detection: A Digital Forensics Approach',
            'authors' => 'Silvialucia Sanna',
            'year' => 2026,
            'venue' => 'Doctoral thesis, Sapienza University of Rome',
            'doi' => '',
            'url' => 'https://hdl.handle.net/20.500.14242/357556',
            'contribution' => 'Informs native-code exploitability triage, memory acquisition planning, stealth malware indicators, anti-analysis resilience, and expert-review controls for intelligent forensic workflows.',
        ],
        [
            'id' => 'gunay-gul-ertam-2026',
            'title' => 'Comparative Analysis of Digital Forensics Methods on Android Devices',
            'authors' => 'Ozge Gunay, Batuhan Gul, Fatih Ertam',
            'year' => 2026,
            'venue' => 'Firat University Journal of Experimental and Computational Engineering, 5(1), 1-25',
            'doi' => '10.62520/fujece.1600312',
            'url' => 'https://dergipark.org.tr/en/pub/fujece/article/1600312',
            'contribution' => 'Shapes the method-comparison model for manual inspection, logical imaging, and physical imaging across nine evidence features.',
        ],
        [
            'id' => 'oh-et-al-2026',
            'title' => 'Forensic Analysis and Evaluation of File-Wiping Applications in Android OS',
            'authors' => 'Dong Bin Oh, Somi Lim, Suji Lee, Yesong Jo, Gahyun Choi, Bumyun Kim, Huy Kang Kim',
            'year' => 2026,
            'venue' => 'Journal of Forensic Sciences, 71(1), 338-352',
            'doi' => '10.1111/1556-4029.70174',
            'url' => 'https://doi.org/10.1111/1556-4029.70174',
            'contribution' => 'Anchors the file-wiping evaluation workflow: claimed behavior, implementation evidence, standards alignment, recoverability, and residual artifacts.',
        ],
        [
            'id' => 'bhardwaj-kaushik-2023',
            'title' => 'Practical Digital Forensics: Forensic Lab Setup, Evidence Analysis, and Structured Investigation Across Windows, Mobile, Browser, HDD, and Memory',
            'authors' => 'Akashdeep Bhardwaj, Keshav Kaushik',
            'year' => 2023,
            'venue' => 'BPB Publications',
            'doi' => '',
            'url' => 'https://reference-global.com/book/9789355511454',
            'contribution' => 'Supports lab operating model design, evidence handling discipline, structured investigation workflow, and broad forensic lab readiness.',
        ],
    ],
    'workflow_stages' => [
        ['id' => 'intake-authority', 'name' => 'Intake and Authority', 'purpose' => 'Capture scope, legal authority, device identifiers, consent, and preservation constraints before touching evidence.'],
        ['id' => 'isolation-preservation', 'name' => 'Isolation and Preservation', 'purpose' => 'Stabilize network exposure, power state, screen-lock state, radios, removable media, and volatile evidence risk.'],
        ['id' => 'acquisition-selection', 'name' => 'Acquisition Selection', 'purpose' => 'Choose manual, logical, file system, physical, cloud, memory, emulator, static, or dynamic techniques based on case needs and constraints.'],
        ['id' => 'tool-validation', 'name' => 'Tool Validation', 'purpose' => 'Record tool version, extraction mode, limitations, hash output, repeatability notes, and independent verification path.'],
        ['id' => 'anti-forensics-review', 'name' => 'Anti-Forensics Review', 'purpose' => 'Evaluate file-wiping, secure deletion claims, obfuscation, steganography, encryption, rooting, and anti-analysis behavior.'],
        ['id' => 'memory-stealth-triage', 'name' => 'Memory and Stealth Triage', 'purpose' => 'Assess volatile evidence, native code risk, malware evasion, root feasibility, and memory acquisition approach.'],
        ['id' => 'correlation-reporting', 'name' => 'Correlation and Reporting', 'purpose' => 'Correlate recovered features across tools, timelines, apps, cloud records, and malware indicators with confidence labels.'],
        ['id' => 'review-retention', 'name' => 'Review and Retention', 'purpose' => 'Apply peer review, privacy minimization, evidence retention, audit logging, and reproducible appendix controls.'],
    ],
    'advanced_modules' => [
        ['id' => 'command-workbench', 'name' => 'Command Workbench', 'mode' => 'Scenario planning', 'description' => 'Converts case signals into an operational lane plan, method sequence, validation backlog, and examiner brief.'],
        ['id' => 'timeline-fusion', 'name' => 'Timeline Fusion', 'mode' => 'Correlation', 'description' => 'Normalizes mixed-source events, clusters them, highlights gaps, and produces reconstruction steps.'],
        ['id' => 'evidence-constellation', 'name' => 'Evidence Constellation', 'mode' => 'Coverage intelligence', 'description' => 'Maps evidence features to roles such as anchor, volatile, recovery, external, and corroboration nodes.'],
        ['id' => 'wiping-claim-lens', 'name' => 'Wiping Claim Lens', 'mode' => 'Anti-forensics', 'description' => 'Separates content recovery, metadata recovery, implementation behavior, and residual execution traces.'],
        ['id' => 'memory-stealth-lane', 'name' => 'Memory Stealth Lane', 'mode' => 'Volatile evidence', 'description' => 'Prioritizes native code, process memory, anti-analysis signals, emulator constraints, and root feasibility.'],
        ['id' => 'integrity-root-ledger', 'name' => 'Integrity Root Ledger', 'mode' => 'Evidence assurance', 'description' => 'Creates deterministic manifest roots for custody checkpoints and report appendices.'],
        ['id' => 'acquisition-feasibility', 'name' => 'Acquisition Feasibility Planner', 'mode' => 'Device state intelligence', 'description' => 'Ranks acquisition paths against Android version, lock state, USB debugging, FBE, cloud authority, and root feasibility.'],
        ['id' => 'artifact-triage-matrix', 'name' => 'Artifact Triage Matrix', 'mode' => 'Parser readiness', 'description' => 'Prioritizes app databases, WAL/SHM files, WebView, E2EE apps, media traces, tokens, and wiping residual artifacts.'],
        ['id' => 'tool-discrepancy-validator', 'name' => 'Tool Discrepancy Validator', 'mode' => 'Quality assurance', 'description' => 'Compares parser outputs, counts, hashes, and confidence to expose disagreement before formal reporting.'],
        ['id' => 'report-readiness-pack', 'name' => 'Report Readiness Pack', 'mode' => 'Defensible reporting', 'description' => 'Scores whether a case file has the authority, hashes, limitations, validation, privacy, and peer review needed for release.'],
    ],
    'evidence_features' => [
        ['id' => 'device-identity', 'name' => 'Device Identity', 'category' => 'System', 'weight' => 7, 'description' => 'Device model, Android build, serials, accounts, carrier, SIM, and lock state.'],
        ['id' => 'installed-apps', 'name' => 'Installed Applications', 'category' => 'Application', 'weight' => 8, 'description' => 'Package inventory, install sources, permissions, signing certificates, app versions, and suspicious packages.'],
        ['id' => 'contacts-accounts', 'name' => 'Contacts and Accounts', 'category' => 'User Data', 'weight' => 6, 'description' => 'Contacts, account bindings, profile artifacts, synced identities, and ownership indicators.'],
        ['id' => 'messages-notifications', 'name' => 'Messages and Notifications', 'category' => 'User Data', 'weight' => 9, 'description' => 'SMS, messaging databases, notification artifacts, chat exports, and end-to-end encryption limitations.'],
        ['id' => 'browser-app-data', 'name' => 'Browser and App Data', 'category' => 'Application', 'weight' => 8, 'description' => 'SQLite databases, WebView storage, cache records, app-specific files, tokens, and local configuration.'],
        ['id' => 'media-metadata', 'name' => 'Media and Metadata', 'category' => 'User Data', 'weight' => 7, 'description' => 'Images, videos, thumbnails, EXIF metadata, media-store records, and residual preview artifacts.'],
        ['id' => 'deleted-unallocated', 'name' => 'Deleted and Unallocated Data', 'category' => 'Recovery', 'weight' => 10, 'description' => 'Recoverable deleted data, file slack, unallocated space, remnants, and overwritten-content limits.'],
        ['id' => 'malware-indicators', 'name' => 'Malware Indicators', 'category' => 'Malware', 'weight' => 9, 'description' => 'Static indicators, dynamic behavior, package anomalies, network callbacks, evasion behavior, and persistence traces.'],
        ['id' => 'cloud-sync-artifacts', 'name' => 'Cloud and Sync Artifacts', 'category' => 'Cloud', 'weight' => 8, 'description' => 'Backups, cloud service records, account synchronization, remote deletion risk, and legal-access requirements.'],
    ],
    'acquisition_methods' => [
        [
            'id' => 'manual-inspection',
            'name' => 'Manual Inspection',
            'access_level' => 'Visible user interface',
            'coverage_hint' => 55.56,
            'strengths' => ['Fast first look', 'Low setup burden', 'Useful for screenshots and visible account state'],
            'limitations' => ['Limited deleted-data recovery', 'High operator dependency', 'Weak repeatability unless carefully recorded'],
            'feature_scores' => [
                'device-identity' => 70,
                'installed-apps' => 65,
                'contacts-accounts' => 60,
                'messages-notifications' => 55,
                'browser-app-data' => 35,
                'media-metadata' => 50,
                'deleted-unallocated' => 10,
                'malware-indicators' => 35,
                'cloud-sync-artifacts' => 45,
            ],
        ],
        [
            'id' => 'logical-acquisition',
            'name' => 'Logical Acquisition',
            'access_level' => 'Accessible files and OS-exposed records',
            'coverage_hint' => 55.56,
            'strengths' => ['Repeatable extraction', 'Lower device risk', 'Strong for current application and user-visible records'],
            'limitations' => ['Limited deleted data', 'Affected by app encryption', 'Tool coverage differs across Android versions'],
            'feature_scores' => [
                'device-identity' => 85,
                'installed-apps' => 80,
                'contacts-accounts' => 75,
                'messages-notifications' => 70,
                'browser-app-data' => 65,
                'media-metadata' => 70,
                'deleted-unallocated' => 20,
                'malware-indicators' => 55,
                'cloud-sync-artifacts' => 60,
            ],
        ],
        [
            'id' => 'file-system-acquisition',
            'name' => 'File System Acquisition',
            'access_level' => 'Application directories and filesystem structure',
            'coverage_hint' => 63.0,
            'strengths' => ['Good app-directory visibility', 'Database and cache access', 'Useful validation layer for logical results'],
            'limitations' => ['Often requires elevated access', 'Device and version dependent', 'Encryption and scoped storage constraints'],
            'feature_scores' => [
                'device-identity' => 80,
                'installed-apps' => 85,
                'contacts-accounts' => 70,
                'messages-notifications' => 72,
                'browser-app-data' => 82,
                'media-metadata' => 78,
                'deleted-unallocated' => 35,
                'malware-indicators' => 70,
                'cloud-sync-artifacts' => 55,
            ],
        ],
        [
            'id' => 'physical-acquisition',
            'name' => 'Physical Imaging',
            'access_level' => 'Block-level storage image',
            'coverage_hint' => 66.67,
            'strengths' => ['Best fit for deleted data', 'Unallocated-space review', 'Strongest storage completeness when feasible'],
            'limitations' => ['Difficult on modern encrypted devices', 'Potentially invasive', 'Requires careful authority and validation'],
            'feature_scores' => [
                'device-identity' => 80,
                'installed-apps' => 82,
                'contacts-accounts' => 75,
                'messages-notifications' => 78,
                'browser-app-data' => 82,
                'media-metadata' => 85,
                'deleted-unallocated' => 92,
                'malware-indicators' => 72,
                'cloud-sync-artifacts' => 35,
            ],
        ],
        [
            'id' => 'cloud-acquisition',
            'name' => 'Cloud Acquisition',
            'access_level' => 'Authorized remote records and backups',
            'coverage_hint' => 52.0,
            'strengths' => ['Captures synced records', 'Can reveal historical backups', 'Useful when device is locked or wiped'],
            'limitations' => ['Requires account authority', 'MFA and legal process dependencies', 'Remote deletion and provider variability'],
            'feature_scores' => [
                'device-identity' => 45,
                'installed-apps' => 50,
                'contacts-accounts' => 82,
                'messages-notifications' => 60,
                'browser-app-data' => 58,
                'media-metadata' => 75,
                'deleted-unallocated' => 15,
                'malware-indicators' => 30,
                'cloud-sync-artifacts' => 92,
            ],
        ],
        [
            'id' => 'memory-acquisition',
            'name' => 'Memory Acquisition',
            'access_level' => 'Volatile system or process memory',
            'coverage_hint' => 48.0,
            'strengths' => ['Potential access to volatile secrets', 'Supports stealth malware review', 'Complements encrypted storage cases'],
            'limitations' => ['Root or exploit constraints', 'Time-sensitive capture', 'High validation burden'],
            'feature_scores' => [
                'device-identity' => 45,
                'installed-apps' => 55,
                'contacts-accounts' => 35,
                'messages-notifications' => 50,
                'browser-app-data' => 50,
                'media-metadata' => 25,
                'deleted-unallocated' => 20,
                'malware-indicators' => 88,
                'cloud-sync-artifacts' => 30,
            ],
        ],
        [
            'id' => 'emulator-dynamic-analysis',
            'name' => 'Emulator Dynamic Analysis',
            'access_level' => 'Controlled execution environment',
            'coverage_hint' => 46.0,
            'strengths' => ['Behavioral observation', 'Network and permission monitoring', 'Repeatable malware experiments'],
            'limitations' => ['Anti-emulator evasion', 'May not reproduce device-specific state', 'Requires containment controls'],
            'feature_scores' => [
                'device-identity' => 30,
                'installed-apps' => 60,
                'contacts-accounts' => 25,
                'messages-notifications' => 30,
                'browser-app-data' => 45,
                'media-metadata' => 25,
                'deleted-unallocated' => 10,
                'malware-indicators' => 86,
                'cloud-sync-artifacts' => 20,
            ],
        ],
        [
            'id' => 'app-static-reverse-engineering',
            'name' => 'Application Static Review',
            'access_level' => 'APK, manifest, bytecode, resources, native libraries',
            'coverage_hint' => 50.0,
            'strengths' => ['Identifies code paths and claims', 'Useful for file-wiping and malware review', 'No execution required'],
            'limitations' => ['Obfuscation can reduce clarity', 'Runtime behavior still needs validation', 'Encrypted or packed code may limit visibility'],
            'feature_scores' => [
                'device-identity' => 20,
                'installed-apps' => 75,
                'contacts-accounts' => 20,
                'messages-notifications' => 20,
                'browser-app-data' => 35,
                'media-metadata' => 30,
                'deleted-unallocated' => 35,
                'malware-indicators' => 88,
                'cloud-sync-artifacts' => 35,
            ],
        ],
        [
            'id' => 'app-dynamic-analysis',
            'name' => 'Application Dynamic Review',
            'access_level' => 'Instrumented runtime behavior',
            'coverage_hint' => 54.0,
            'strengths' => ['Validates behavior against claims', 'Captures file and network activity', 'Supports anti-analysis checks'],
            'limitations' => ['Needs safe lab containment', 'Runtime conditions influence results', 'Instrumentation can be detected'],
            'feature_scores' => [
                'device-identity' => 25,
                'installed-apps' => 65,
                'contacts-accounts' => 30,
                'messages-notifications' => 35,
                'browser-app-data' => 55,
                'media-metadata' => 40,
                'deleted-unallocated' => 45,
                'malware-indicators' => 92,
                'cloud-sync-artifacts' => 40,
            ],
        ],
    ],
    'tool_profiles' => [
        ['id' => 'magnet-axiom', 'name' => 'Magnet AXIOM', 'category' => 'Commercial suite', 'use_case' => 'Logical, file-system, artifact parsing, timeline analysis, and reporting validation.'],
        ['id' => 'belkasoft-x', 'name' => 'Belkasoft X', 'category' => 'Commercial suite', 'use_case' => 'Mobile artifact parsing, media review, chat artifacts, and cross-source case analysis.'],
        ['id' => 'cellebrite-ufed', 'name' => 'Cellebrite UFED', 'category' => 'Commercial extraction', 'use_case' => 'Logical, file-system, and supported physical acquisition workflows.'],
        ['id' => 'andriller', 'name' => 'Andriller', 'category' => 'Focused extraction', 'use_case' => 'Android logical acquisition and selected artifact parsing.'],
        ['id' => 'aflogical', 'name' => 'AFLogical', 'category' => 'Open-source extraction', 'use_case' => 'Logical acquisition for selected Android datasets.'],
        ['id' => 'autopsy-sleuth-kit', 'name' => 'Autopsy and The Sleuth Kit', 'category' => 'Open-source analysis', 'use_case' => 'Filesystem review, timeline correlation, hash sets, keyword search, and reporting.'],
        ['id' => 'jadx-dex2jar', 'name' => 'JADX and dex2jar', 'category' => 'Reverse engineering', 'use_case' => 'APK static analysis, manifest review, bytecode inspection, and file-wiping claim validation.'],
        ['id' => 'frida-strace', 'name' => 'Frida and strace', 'category' => 'Runtime instrumentation', 'use_case' => 'Dynamic behavior observation, API tracing, file access review, and anti-analysis experiments.'],
        ['id' => 'memory-acquisition-toolkit', 'name' => 'Android Memory Acquisition Toolkit', 'category' => 'Volatile evidence', 'use_case' => 'Process or full-memory capture planning, memory artifact review, and stealth behavior triage.'],
        ['id' => 'hash-ledger', 'name' => 'Hash Ledger and Merkle Manifest', 'category' => 'Integrity control', 'use_case' => 'Evidence inventory integrity, manifest comparison, peer review, and custody checkpoints.'],
    ],
    'wiping_artifacts' => [
        ['id' => 'declared-claim', 'name' => 'Declared Wiping Claim', 'category' => 'Static Review', 'description' => 'Public claim, UI text, permissions, and application wording around deletion or wiping.'],
        ['id' => 'overwrite-pattern', 'name' => 'Overwrite Pattern Evidence', 'category' => 'Dynamic Review', 'description' => 'Observed writes, passes, patterns, randomness, file-handle behavior, and sync/fsync handling.'],
        ['id' => 'standards-alignment', 'name' => 'Standards Alignment', 'category' => 'Compliance Review', 'description' => 'Comparison with applicable wiping expectations, media constraints, and documented algorithm behavior.'],
        ['id' => 'recoverability-result', 'name' => 'Recoverability Result', 'category' => 'Validation', 'description' => 'Recovered content, partial recovery, metadata recovery, and hash comparison after tool execution.'],
        ['id' => 'app-internal-artifacts', 'name' => 'Application Internal Artifacts', 'category' => 'Residual Artifacts', 'description' => 'Databases, preferences, logs, cache, and execution state left by the wiping application.'],
        ['id' => 'os-execution-artifacts', 'name' => 'OS Execution Artifacts', 'category' => 'Residual Artifacts', 'description' => 'Package state, recent tasks, notifications, filesystem timestamps, thumbnails, and media-store traces.'],
        ['id' => 'network-artifacts', 'name' => 'Network and Telemetry Artifacts', 'category' => 'Residual Artifacts', 'description' => 'Remote calls, telemetry, update checks, ads, analytics endpoints, and execution context.'],
        ['id' => 'timeline-consistency', 'name' => 'Timeline Consistency', 'category' => 'Correlation', 'description' => 'Event ordering between original file creation, wiping execution, post-wipe traces, and acquisition time.'],
    ],
    'forensic_controls' => [
        ['id' => 'legal-authority', 'name' => 'Document Legal Authority', 'category' => 'Governance', 'weight' => 10, 'description' => 'Record authority, scope, consent, and limits before acquisition.'],
        ['id' => 'case-scope', 'name' => 'Define Case Scope', 'category' => 'Governance', 'weight' => 7, 'description' => 'Document devices, accounts, apps, dates, questions, and exclusions.'],
        ['id' => 'privacy-minimization', 'name' => 'Privacy Minimization', 'category' => 'Governance', 'weight' => 7, 'description' => 'Limit review and exports to relevant artifacts, with handling rules for sensitive content.'],
        ['id' => 'chain-of-custody', 'name' => 'Chain of Custody', 'category' => 'Evidence Handling', 'weight' => 10, 'description' => 'Record every transfer, handler, storage location, and evidence seal.'],
        ['id' => 'device-isolation', 'name' => 'Device Isolation Plan', 'category' => 'Evidence Handling', 'weight' => 8, 'description' => 'Control radios, remote wipe risk, notifications, power, and environmental state.'],
        ['id' => 'photographic-record', 'name' => 'Photographic Record', 'category' => 'Evidence Handling', 'weight' => 5, 'description' => 'Capture device condition, identifiers, screen state, accessories, and packaging.'],
        ['id' => 'hash-manifest', 'name' => 'Hash Manifest', 'category' => 'Evidence Integrity', 'weight' => 10, 'description' => 'Create SHA-256 manifests for extracted files, images, exports, and reports.'],
        ['id' => 'merkle-root', 'name' => 'Merkle Manifest Root', 'category' => 'Evidence Integrity', 'weight' => 8, 'description' => 'Create a compact integrity root over normalized evidence manifests.'],
        ['id' => 'independent-verification', 'name' => 'Independent Verification', 'category' => 'Evidence Integrity', 'weight' => 9, 'description' => 'Use a second tool or manual validation for high-value artifacts and negative findings.'],
        ['id' => 'tool-version-record', 'name' => 'Tool Version Record', 'category' => 'Tool Validation', 'weight' => 6, 'description' => 'Record tool names, versions, profiles, extraction mode, plugins, and parsing limitations.'],
        ['id' => 'tool-coverage-matrix', 'name' => 'Tool Coverage Matrix', 'category' => 'Tool Validation', 'weight' => 8, 'description' => 'Map tools and methods to evidence features, gaps, and validation steps.'],
        ['id' => 'method-selection-rationale', 'name' => 'Method Selection Rationale', 'category' => 'Acquisition', 'weight' => 9, 'description' => 'Explain why selected acquisition methods fit the device state and case questions.'],
        ['id' => 'logical-acquisition', 'name' => 'Logical Acquisition Record', 'category' => 'Acquisition', 'weight' => 6, 'description' => 'Record logical extraction output, limitations, available datasets, and verification steps.'],
        ['id' => 'file-system-acquisition', 'name' => 'File-System Acquisition Record', 'category' => 'Acquisition', 'weight' => 7, 'description' => 'Capture filesystem-level artifacts, app directories, databases, caches, and limitations.'],
        ['id' => 'physical-acquisition', 'name' => 'Physical Imaging Record', 'category' => 'Acquisition', 'weight' => 8, 'description' => 'Record physical image feasibility, encryption limits, procedure, and examiner notes.'],
        ['id' => 'cloud-authority', 'name' => 'Cloud Authority and Sync Review', 'category' => 'Acquisition', 'weight' => 7, 'description' => 'Track cloud scope, authorization, MFA constraints, exports, and remote deletion risk.'],
        ['id' => 'memory-capture-plan', 'name' => 'Memory Capture Plan', 'category' => 'Memory Forensics', 'weight' => 8, 'description' => 'Plan process or full-memory capture, root constraints, timing, tooling, and validation.'],
        ['id' => 'native-code-risk', 'name' => 'Native Code Risk Review', 'category' => 'Memory Forensics', 'weight' => 8, 'description' => 'Review native libraries, risky C/C++ patterns, exploitability indicators, and memory exposure.'],
        ['id' => 'anti-analysis-checks', 'name' => 'Anti-Analysis Checks', 'category' => 'Malware and Stealth', 'weight' => 8, 'description' => 'Check obfuscation, emulator detection, root checks, packed code, staged payloads, and adversarial behavior.'],
        ['id' => 'static-malware-review', 'name' => 'Static Malware Review', 'category' => 'Malware and Stealth', 'weight' => 7, 'description' => 'Review manifest, permissions, bytecode, native libraries, signing, strings, and configuration.'],
        ['id' => 'dynamic-malware-review', 'name' => 'Dynamic Malware Review', 'category' => 'Malware and Stealth', 'weight' => 8, 'description' => 'Observe runtime file, network, permission, service, persistence, and evasion behavior.'],
        ['id' => 'wiping-claim-review', 'name' => 'Wiping Claim Review', 'category' => 'Anti-Forensics', 'weight' => 7, 'description' => 'Compare app claims with static code, runtime writes, recoverability, and residual artifacts.'],
        ['id' => 'recoverability-test', 'name' => 'Recoverability Test', 'category' => 'Anti-Forensics', 'weight' => 8, 'description' => 'Test whether content or metadata remains recoverable after deletion or wiping activity.'],
        ['id' => 'standards-review', 'name' => 'Wiping Standards Review', 'category' => 'Anti-Forensics', 'weight' => 6, 'description' => 'Document whether the wiping implementation follows documented method expectations and limitations.'],
        ['id' => 'timeline-correlation', 'name' => 'Timeline Correlation', 'category' => 'Analysis', 'weight' => 8, 'description' => 'Correlate file, app, OS, cloud, network, and acquisition timestamps with timezone normalization.'],
        ['id' => 'confidence-labels', 'name' => 'Confidence Labels', 'category' => 'Analysis', 'weight' => 6, 'description' => 'Label findings as confirmed, probable, possible, unsupported, or excluded with reasoning.'],
        ['id' => 'limitations-statement', 'name' => 'Limitations Statement', 'category' => 'Reporting', 'weight' => 7, 'description' => 'Document encryption, tool gaps, acquisition limits, missing context, and negative findings.'],
        ['id' => 'peer-review', 'name' => 'Peer Review', 'category' => 'Reporting', 'weight' => 8, 'description' => 'Require independent technical review before release of formal results.'],
        ['id' => 'reproducible-appendix', 'name' => 'Reproducible Appendix', 'category' => 'Reporting', 'weight' => 7, 'description' => 'Include procedures, commands, hashes, tool settings, dataset paths, and evidence references.'],
        ['id' => 'audit-retention', 'name' => 'Audit and Retention Plan', 'category' => 'Operations', 'weight' => 6, 'description' => 'Retain audit records, decisions, evidence manifests, reports, and review notes according to policy.'],
    ],
    'report_dimensions' => [
        'Authority, scope, and preservation',
        'Device profile and operating state',
        'Acquisition methods and tool coverage',
        'Anti-forensics and wiping evaluation',
        'Memory, stealth, and native-code findings',
        'Recovered features and validation evidence',
        'Evidence integrity and chain-of-custody records',
        'Limitations, confidence, and recommended next steps',
    ],
];
